using Microsoft.Data.Sqlite;
using Workbench.Storage.Database;
using Workbench.Storage.Tests.Database;
using Workbench.Storage.Workers;

namespace Workbench.Storage.Tests.Workers;
public sealed class CompletionPackageTests
{
 [Fact] public async Task Package_roundtrips_report_and_evidence_separately(){await using var f=await Fixture.CreateAsync();await f.Packages.AddAsync(f.PackageId,f.Execution,f.Task,f.Revision,"report says HEAD=abc","{\"schema_version\":1,\"WorkerFinalHead\":\"def\"}");var p=await f.Packages.GetByExecutionAsync(f.Project,f.Execution);Assert.Equal("report says HEAD=abc",p!.Report);Assert.Contains("def",p.Evidence);}
 [Fact] public async Task Duplicate_execution_package_is_rejected_and_cross_task_revision_fails(){await using var f=await Fixture.CreateAsync();await f.Packages.AddAsync(f.PackageId,f.Execution,f.Task,f.Revision,"r","{\"schema_version\":1}");await Assert.ThrowsAsync<SqliteException>(()=>f.Packages.AddAsync(Guid.NewGuid(),f.Execution,f.Task,f.Revision,"r2","{\"schema_version\":1}"));await Assert.ThrowsAsync<InvalidOperationException>(()=>f.Packages.AddAsync(Guid.NewGuid(),f.Execution,Guid.NewGuid(),f.Revision,"r","{\"schema_version\":1}"));}
 private sealed class Fixture:IAsyncDisposable{readonly TemporaryDatabase T;public readonly WorkbenchDatabase Db;public readonly CompletionPackageRepository Packages;public readonly Guid Project=Guid.NewGuid(),Task=Guid.NewGuid(),Execution=Guid.NewGuid(),Revision=Guid.NewGuid(),PackageId=Guid.NewGuid();Fixture(TemporaryDatabase t,WorkbenchDatabase d){T=t;Db=d;Packages=new(d);}public static async Task<Fixture>CreateAsync(){var t=new TemporaryDatabase();var d=new WorkbenchDatabase(t.DatabasePath);await d.InitializeAsync();var f=new Fixture(t,d);await using var c=d.CreateConnection();await c.OpenAsync();var q=c.CreateCommand();q.CommandText=$"INSERT INTO projects(id,name,root_path,project_type,created_at,last_opened_at) VALUES('{f.Project}','P','C:/P',0,'2026-01-01T00:00:00+00:00','2026-01-01T00:00:00+00:00'); INSERT INTO tasks(id,project_id,title,status,current_revision_id,created_at,updated_at) VALUES('{f.Task}','{f.Project}','T','Draft','{f.Revision}','2026-01-01T00:00:00+00:00','2026-01-01T00:00:00+00:00'); INSERT INTO task_revisions(id,task_id,revision_number,goal,scope,out_of_scope,acceptance_json,risk_level,recommended_provider_id,recommended_provider_account_id,recommended_model_profile_id,recommended_agent_runtime_id,change_reason,approved_by,created_at) VALUES('{f.Revision}','{f.Task}',1,'g','s','o','[\\\"a\\\"]','Low','p','a','m','r','c','User','2026-01-01T00:00:00+00:00'); INSERT INTO worker_executions(id,project_id,task_id,execution_start_revision_id,execution_start_revision_number,current_ack_revision_id,current_ack_revision_number,base_commit,target_branch,provider_id,provider_account_id,model_profile_id,agent_runtime_id,worker_branch,worker_worktree_path,state,created_at,updated_at) VALUES('{f.Execution}','{f.Project}','{f.Task}','{f.Revision}',1,'{f.Revision}',1,'base','master','p','a','m','r','branch','C:/P/worker','Preparing','2026-01-01T00:00:00+00:00','2026-01-01T00:00:00+00:00');";await q.ExecuteNonQueryAsync();return f;}public ValueTask DisposeAsync()=>T.DisposeAsync();}
}
