using Workbench.Core.Workers;
using Workbench.Storage.Database;
using Workbench.Storage.Tests.Database;
using Workbench.Storage.Workers;

namespace Workbench.Storage.Tests.Workers;
public sealed class TaskEventPermissionClarificationTests
{
 [Fact] public async Task Events_are_idempotent_and_ordered(){await using var f=await Fixture.CreateAsync();var a=new StoredTaskEvent(Guid.NewGuid(),f.Project,f.Task,null,"StateTransition","a",DateTimeOffset.UtcNow);var b=a with {EventId=Guid.NewGuid(),Payload="b",CreatedAt=a.CreatedAt};await f.Events.AppendAsync(a);await f.Events.AppendAsync(a);await f.Events.AppendAsync(b);var list=await f.Events.ListAsync(f.Project,f.Task,10);Assert.Equal(2,list.Count);Assert.Equal(new[]{a.EventId,b.EventId}.OrderBy(x=>x),list.Select(x=>x.EventId));}
 [Fact] public async Task Permission_roundtrip_and_atomic_resolution(){await using var f=await Fixture.CreateAsync();var p=new PermissionRequest(f.Task,1,"ReadProject","task",PermissionAccessMode.Read,"why",PermissionRisk.Low,TimeSpan.FromMinutes(2),DateTimeOffset.UtcNow);var id=Guid.NewGuid();await f.Permissions.AddAsync(f.Project,id,p);Assert.True(await f.Permissions.ResolveAsync(f.Project,f.Task,id,"Approved","user"));Assert.False(await f.Permissions.ResolveAsync(f.Project,f.Task,id,"Denied","user"));}
 [Fact] public async Task Grant_lookup_is_task_scoped_and_expiry_aware(){await using var f=await Fixture.CreateAsync();var id=Guid.NewGuid();await f.Grants.AddAsync(f.Project,id,new TaskGrant(f.Task,"ReadProject","task",DateTimeOffset.UtcNow.AddMinutes(1)),"user");Assert.True(await f.Grants.HasActiveGrantAsync(f.Project,f.Task,"ReadProject","task",DateTimeOffset.UtcNow));Assert.False(await f.Grants.HasActiveGrantAsync(f.Project,Guid.NewGuid(),"ReadProject","task",DateTimeOffset.UtcNow));}
 [Fact] public async Task Clarification_is_separate_and_does_not_create_revision(){await using var f=await Fixture.CreateAsync();var c=new TaskClarificationRequest(f.Task,1,"unclear",TaskClarificationCategory.GoalAmbiguity,DateTimeOffset.UtcNow);await f.Clarifications.AddAsync(f.Project,Guid.NewGuid(),c,"reason");Assert.Single(await f.Clarifications.ListAsync(f.Project,f.Task));}
 private sealed class Fixture:IAsyncDisposable{readonly TemporaryDatabase T;public readonly Guid Project=Guid.NewGuid(),Task=Guid.NewGuid();public readonly TaskEventRepository Events;public readonly PermissionRepository Permissions;public readonly TaskGrantRepository Grants;public readonly TaskClarificationRepository Clarifications;Fixture(TemporaryDatabase t,WorkbenchDatabase d){T=t;Events=new(d);Permissions=new(d);Grants=new(d);Clarifications=new(d);}public static async Task<Fixture>CreateAsync(){var t=new TemporaryDatabase();var d=new WorkbenchDatabase(t.DatabasePath);await d.InitializeAsync();var f=new Fixture(t,d);await using var c=d.CreateConnection();await c.OpenAsync();var q=c.CreateCommand();q.CommandText=$"INSERT INTO projects(id,name,root_path,project_type,created_at,last_opened_at) VALUES('{f.Project}','P','C:/P',0,'2026-01-01T00:00:00+00:00','2026-01-01T00:00:00+00:00'); INSERT INTO tasks(id,project_id,title,status,current_revision_id,created_at,updated_at) VALUES('{f.Task}','{f.Project}','T','Draft','{Guid.NewGuid()}','2026-01-01T00:00:00+00:00','2026-01-01T00:00:00+00:00');";await q.ExecuteNonQueryAsync();return f;}public ValueTask DisposeAsync()=>T.DisposeAsync();}
}
