using System.Globalization;
using Microsoft.Data.Sqlite;
using Workbench.Core.Tasks;
using Workbench.Core.Workers;
using Workbench.Storage.Database;

namespace Workbench.Storage.Workers;
public sealed record StoredWorkerExecution(Guid ExecutionId,Guid ProjectId,Guid TaskId,TaskRevisionReference ExecutionStartRevision,TaskRevisionReference CurrentAcknowledgedRevision,string BaseCommit,string TargetBranch,ProviderAccountBinding ProviderAccount,ExecutionProfile ExecutionProfile,string WorkerBranch,string WorkerWorktreePath,WorkerExecutionState State,string? AgentSessionId,string? ExternalSessionId,string? WorkingDirectory,DateTimeOffset CreatedAt,DateTimeOffset UpdatedAt);
public sealed class WorkerExecutionRepository(WorkbenchDatabase database)
{
 private readonly WorkbenchDatabase _database=database;
 public async Task CreateAsync(StoredWorkerExecution e,CancellationToken ct=default){if(e.State==WorkerExecutionState.Running&&(string.IsNullOrWhiteSpace(e.AgentSessionId)||string.IsNullOrWhiteSpace(e.WorkingDirectory)))throw new InvalidOperationException("Running execution requires session identity and working directory.");await using var c=_database.CreateConnection();await c.OpenAsync(ct);var q=c.CreateCommand();q.CommandText="INSERT INTO worker_executions(id,project_id,task_id,execution_start_revision_id,execution_start_revision_number,current_ack_revision_id,current_ack_revision_number,base_commit,target_branch,provider_id,provider_account_id,model_profile_id,agent_runtime_id,worker_branch,worker_worktree_path,state,agent_session_id,external_session_id,working_directory,created_at,updated_at) VALUES($id,$p,$t,$sr,$sn,$cr,$cn,$b,$tb,$pid,$pa,$m,$a,$wb,$ww,$s,$as,$es,$wd,$ca,$ua)";q.Parameters.AddWithValue("$id",e.ExecutionId.ToString());q.Parameters.AddWithValue("$p",e.ProjectId.ToString());q.Parameters.AddWithValue("$t",e.TaskId.ToString());q.Parameters.AddWithValue("$sr",e.ExecutionStartRevision.RevisionId.ToString());q.Parameters.AddWithValue("$sn",e.ExecutionStartRevision.RevisionNumber);q.Parameters.AddWithValue("$cr",e.CurrentAcknowledgedRevision.RevisionId.ToString());q.Parameters.AddWithValue("$cn",e.CurrentAcknowledgedRevision.RevisionNumber);q.Parameters.AddWithValue("$b",e.BaseCommit);q.Parameters.AddWithValue("$tb",e.TargetBranch);q.Parameters.AddWithValue("$pid",e.ProviderAccount.ProviderId);q.Parameters.AddWithValue("$pa",e.ProviderAccount.AccountId);q.Parameters.AddWithValue("$m",e.ExecutionProfile.ModelProfileId);q.Parameters.AddWithValue("$a",e.ExecutionProfile.AgentRuntimeId);q.Parameters.AddWithValue("$wb",e.WorkerBranch);q.Parameters.AddWithValue("$ww",e.WorkerWorktreePath);q.Parameters.AddWithValue("$s",e.State.ToString());q.Parameters.AddWithValue("$as",(object?)e.AgentSessionId??DBNull.Value);q.Parameters.AddWithValue("$es",(object?)e.ExternalSessionId??DBNull.Value);q.Parameters.AddWithValue("$wd",(object?)e.WorkingDirectory??DBNull.Value);q.Parameters.AddWithValue("$ca",e.CreatedAt.ToString("O"));q.Parameters.AddWithValue("$ua",e.UpdatedAt.ToString("O"));await q.ExecuteNonQueryAsync(ct);}
 public async Task<StoredWorkerExecution?> GetAsync(Guid projectId,Guid executionId,CancellationToken ct=default){await using var c=_database.CreateConnection();await c.OpenAsync(ct);var q=c.CreateCommand();q.CommandText="SELECT id,project_id,task_id,execution_start_revision_id,execution_start_revision_number,current_ack_revision_id,current_ack_revision_number,base_commit,target_branch,provider_id,provider_account_id,model_profile_id,agent_runtime_id,worker_branch,worker_worktree_path,state,agent_session_id,external_session_id,working_directory,created_at,updated_at FROM worker_executions WHERE project_id=$p AND id=$i";q.Parameters.AddWithValue("$p",projectId.ToString());q.Parameters.AddWithValue("$i",executionId.ToString());await using var r=await q.ExecuteReaderAsync(ct);if(!await r.ReadAsync(ct))return null;return new StoredWorkerExecution(Guid.Parse(r.GetString(0)),Guid.Parse(r.GetString(1)),Guid.Parse(r.GetString(2)),new TaskRevisionReference(Guid.Parse(r.GetString(2)),Guid.Parse(r.GetString(3)),r.GetInt32(4)),new TaskRevisionReference(Guid.Parse(r.GetString(2)),Guid.Parse(r.GetString(6-1)),r.GetInt32(6)),r.GetString(7),r.GetString(8),ProviderAccountBinding.Create(r.GetString(9),r.GetString(10)),ExecutionProfile.Create(r.GetString(9),r.GetString(10),r.GetString(11),r.GetString(12)),r.GetString(13),r.GetString(14),Enum.Parse<WorkerExecutionState>(r.GetString(15)),r.IsDBNull(16)?null:r.GetString(16),r.IsDBNull(17)?null:r.GetString(17),r.IsDBNull(18)?null:r.GetString(18),DateTimeOffset.Parse(r.GetString(19)),DateTimeOffset.Parse(r.GetString(20)));}
 public async Task UpdateStateAsync(Guid projectId,Guid taskId,Guid id,WorkerExecutionState state,CancellationToken ct=default){var current=await GetAsync(projectId,id,ct)??throw new KeyNotFoundException();if(current.TaskId!=taskId)throw new InvalidOperationException("Execution task mismatch.");if(state==WorkerExecutionState.Running){if(string.IsNullOrWhiteSpace(current.AgentSessionId)||string.IsNullOrWhiteSpace(current.WorkingDirectory)||!SamePath(current.WorkingDirectory,current.WorkerWorktreePath))throw new InvalidOperationException("Running execution requires matching session identity and worktree.");}await using var c=_database.CreateConnection();await c.OpenAsync(ct);var q=c.CreateCommand();q.CommandText="UPDATE worker_executions SET state=$s,updated_at=$a WHERE project_id=$p AND task_id=$t AND id=$i";q.Parameters.AddWithValue("$s",state.ToString());q.Parameters.AddWithValue("$a",DateTimeOffset.UtcNow.ToString("O"));q.Parameters.AddWithValue("$p",projectId.ToString());q.Parameters.AddWithValue("$t",taskId.ToString());q.Parameters.AddWithValue("$i",id.ToString());await q.ExecuteNonQueryAsync(ct);}
 public async Task PersistSessionIdentityAsync(Guid projectId,Guid taskId,Guid id,string? agent,string? external,string workingDirectory,CancellationToken ct=default){if(string.IsNullOrWhiteSpace(workingDirectory))throw new ArgumentException("Working directory required",nameof(workingDirectory));await using var c=_database.CreateConnection();await c.OpenAsync(ct);var q=c.CreateCommand();q.CommandText="UPDATE worker_executions SET agent_session_id=$a,external_session_id=$e,working_directory=$w,updated_at=$u WHERE project_id=$p AND task_id=$t AND id=$i";q.Parameters.AddWithValue("$a",(object?)agent??DBNull.Value);q.Parameters.AddWithValue("$e",(object?)external??DBNull.Value);q.Parameters.AddWithValue("$w",workingDirectory);q.Parameters.AddWithValue("$u",DateTimeOffset.UtcNow.ToString("O"));q.Parameters.AddWithValue("$p",projectId.ToString());q.Parameters.AddWithValue("$t",taskId.ToString());q.Parameters.AddWithValue("$i",id.ToString());await q.ExecuteNonQueryAsync(ct);}
 private static bool SamePath(string a,string b){var x=Path.GetFullPath(a).TrimEnd(Path.DirectorySeparatorChar,Path.AltDirectorySeparatorChar);var y=Path.GetFullPath(b).TrimEnd(Path.DirectorySeparatorChar,Path.AltDirectorySeparatorChar);return OperatingSystem.IsWindows()?string.Equals(x,y,StringComparison.OrdinalIgnoreCase):string.Equals(x,y,StringComparison.Ordinal);}
 public async Task<bool> AcknowledgeAsync(Guid executionId,Guid taskId,int expected,int target,Guid revisionId,CancellationToken ct=default){await using var c=_database.CreateConnection();await c.OpenAsync(ct);var q=c.CreateCommand();q.CommandText="UPDATE worker_executions SET current_ack_revision_id=$r,current_ack_revision_number=$n,updated_at=$at WHERE id=$id AND task_id=$t AND current_ack_revision_number=$expected AND $n>current_ack_revision_number AND EXISTS(SELECT 1 FROM task_revisions r WHERE r.id=$r AND r.task_id=$t AND r.revision_number=$n)";q.Parameters.AddWithValue("$r",revisionId.ToString());q.Parameters.AddWithValue("$n",target);q.Parameters.AddWithValue("$expected",expected);q.Parameters.AddWithValue("$id",executionId.ToString());q.Parameters.AddWithValue("$t",taskId.ToString());q.Parameters.AddWithValue("$at",DateTimeOffset.UtcNow.ToString("O"));return await q.ExecuteNonQueryAsync(ct)==1;}
 public async Task<bool> AdvanceAcknowledgedRevisionAsync(Guid projectId,Guid taskId,Guid executionId,int expectedCurrentRevision,Guid targetRevision,int targetRevisionNumber,CancellationToken ct=default)
 {
  await using var connection=_database.CreateConnection(); await connection.OpenAsync(ct); await using var transaction=await connection.BeginTransactionAsync(ct);
  var command=connection.CreateCommand(); command.Transaction=(SqliteTransaction)transaction;
  command.CommandText="UPDATE worker_executions SET current_ack_revision_id=$target,current_ack_revision_number=$targetNumber,updated_at=$updated WHERE project_id=$project AND task_id=$task AND id=$execution AND current_ack_revision_number=$expected AND $targetNumber > current_ack_revision_number AND EXISTS (SELECT 1 FROM task_revisions revision WHERE revision.id=$target AND revision.task_id=$task AND revision.revision_number=$targetNumber);";
  command.Parameters.AddWithValue("$target",targetRevision.ToString()); command.Parameters.AddWithValue("$targetNumber",targetRevisionNumber); command.Parameters.AddWithValue("$expected",expectedCurrentRevision); command.Parameters.AddWithValue("$project",projectId.ToString()); command.Parameters.AddWithValue("$task",taskId.ToString()); command.Parameters.AddWithValue("$execution",executionId.ToString()); command.Parameters.AddWithValue("$updated",DateTimeOffset.UtcNow.ToString("O"));
  var changed=await command.ExecuteNonQueryAsync(ct)==1; await transaction.CommitAsync(ct); return changed;
 }
}
