using System.Globalization;
using Microsoft.Data.Sqlite;
using Workbench.Storage.Database;
namespace Workbench.Storage.Memory;
public sealed class LeaderEpochContinuityRepository(WorkbenchDatabase database)
{
    private readonly WorkbenchDatabase _database=database;
    public async Task SaveAsync(Guid projectId, LeaderEpochContinuityPlan plan, CancellationToken cancellationToken=default)
    { await using var c=_database.CreateConnection(); await c.OpenAsync(cancellationToken); await using var tx=(SqliteTransaction)await c.BeginTransactionAsync(cancellationToken); try { var check=c.CreateCommand();check.Transaction=tx;check.CommandText="SELECT COUNT(*) FROM leader_session_epochs WHERE id=$id AND project_id=$project;";check.Parameters.AddWithValue("$id",plan.EpochId.ToString());check.Parameters.AddWithValue("$project",projectId.ToString());if(Convert.ToInt64(await check.ExecuteScalarAsync(cancellationToken))!=1)throw new InvalidOperationException("The epoch is not owned by this project.");var head=c.CreateCommand();head.Transaction=tx;head.CommandText="INSERT INTO leader_epoch_continuity_plans VALUES($id,$total,$created) ON CONFLICT(epoch_id) DO UPDATE SET total_max_utf8_bytes=excluded.total_max_utf8_bytes,created_at=excluded.created_at;";head.Parameters.AddWithValue("$id",plan.EpochId.ToString());head.Parameters.AddWithValue("$total",plan.TotalMaxUtf8Bytes);head.Parameters.AddWithValue("$created",plan.CreatedAt.ToString("O",CultureInfo.InvariantCulture));await head.ExecuteNonQueryAsync(cancellationToken);var del=c.CreateCommand();del.Transaction=tx;del.CommandText="DELETE FROM leader_epoch_continuity_selections WHERE epoch_id=$id;";del.Parameters.AddWithValue("$id",plan.EpochId.ToString());await del.ExecuteNonQueryAsync(cancellationToken);foreach(var s in plan.Selections.OrderBy(x=>x.Ordinal)){var q=c.CreateCommand();q.Transaction=tx;q.CommandText="INSERT INTO leader_epoch_continuity_selections VALUES($id,$ordinal,$kind,$reference,$max,$selector);";q.Parameters.AddWithValue("$id",plan.EpochId.ToString());q.Parameters.AddWithValue("$ordinal",s.Ordinal);q.Parameters.AddWithValue("$kind",s.Kind.ToString());q.Parameters.AddWithValue("$reference",s.Reference);q.Parameters.AddWithValue("$max",s.MaxUtf8Bytes);q.Parameters.AddWithValue("$selector",(object?)s.SelectorJson??DBNull.Value);await q.ExecuteNonQueryAsync(cancellationToken);}await tx.CommitAsync(cancellationToken);}catch{await tx.RollbackAsync(CancellationToken.None);throw;} }
    public async Task<LeaderEpochContinuityPlan?> GetAsync(Guid projectId, Guid epochId, CancellationToken cancellationToken=default)
    { await using var c=_database.CreateConnection();await c.OpenAsync(cancellationToken);var h=c.CreateCommand();h.CommandText="SELECT p.total_max_utf8_bytes,p.created_at FROM leader_epoch_continuity_plans p JOIN leader_session_epochs e ON e.id=p.epoch_id WHERE p.epoch_id=$id AND e.project_id=$project;";h.Parameters.AddWithValue("$id",epochId.ToString());h.Parameters.AddWithValue("$project",projectId.ToString());await using var r=await h.ExecuteReaderAsync(cancellationToken);if(!await r.ReadAsync(cancellationToken))return null;var total=r.GetInt32(0);var created=DateTimeOffset.Parse(r.GetString(1),CultureInfo.InvariantCulture);var q=c.CreateCommand();q.CommandText="SELECT ordinal,material_kind,material_ref,max_utf8_bytes,selector_json FROM leader_epoch_continuity_selections WHERE epoch_id=$id ORDER BY ordinal;";q.Parameters.AddWithValue("$id",epochId.ToString());await using var s=await q.ExecuteReaderAsync(cancellationToken);var all=new List<ContinuityMaterialSelection>();while(await s.ReadAsync(cancellationToken))all.Add(new(s.GetInt32(0),Enum.Parse<ContinuityMaterialKind>(s.GetString(1)),s.GetString(2),s.GetInt32(3),s.IsDBNull(4)?null:s.GetString(4)));return new(epochId,total,all,created); }
}
