using System.Globalization;
using Microsoft.Data.Sqlite;
using Workbench.Storage.Database;

namespace Workbench.Storage.Memory;

public sealed class ProjectMemoryRepository(WorkbenchDatabase database)
{
    private readonly WorkbenchDatabase _database = database;
    public async Task AddAsync(ProjectMemoryItem item, IReadOnlyList<ProjectMemorySource> sources, CancellationToken cancellationToken = default)
    {
        await using var c = _database.CreateConnection(); await c.OpenAsync(cancellationToken); await using var tx = await c.BeginTransactionAsync(cancellationToken);
        var q = c.CreateCommand(); q.Transaction = (SqliteTransaction)tx; q.CommandText = "INSERT INTO project_memory_items VALUES ($id,$project,$layer,$topic,$content,$status,$created,$updated,$certified);"; Add(q,item); await q.ExecuteNonQueryAsync(cancellationToken);
        foreach (var source in sources) { var s=c.CreateCommand(); s.Transaction=(SqliteTransaction)tx; s.CommandText="INSERT INTO project_memory_sources VALUES ($id,$type,$ref);"; s.Parameters.AddWithValue("$id",item.Id.ToString()); s.Parameters.AddWithValue("$type",source.SourceType); s.Parameters.AddWithValue("$ref",source.SourceRef); await s.ExecuteNonQueryAsync(cancellationToken); }
        await tx.CommitAsync(cancellationToken);
    }
    public async Task<ProjectMemoryItem?> GetAsync(Guid id, CancellationToken cancellationToken=default) { await using var c=_database.CreateConnection(); await c.OpenAsync(cancellationToken); var q=c.CreateCommand();q.CommandText="SELECT id,project_id,layer,topic,content,status,created_at,updated_at,certified_at FROM project_memory_items WHERE id=$id;";q.Parameters.AddWithValue("$id",id.ToString());await using var r=await q.ExecuteReaderAsync(cancellationToken);return await r.ReadAsync(cancellationToken)?Read(r):null; }
    public async Task<IReadOnlyList<ProjectMemoryItem>> GetAsync(Guid projectId,string layer,string status,CancellationToken cancellationToken=default){await using var c=_database.CreateConnection();await c.OpenAsync(cancellationToken);var q=c.CreateCommand();q.CommandText="SELECT id,project_id,layer,topic,content,status,created_at,updated_at,certified_at FROM project_memory_items WHERE project_id=$project AND layer=$layer AND status=$status ORDER BY created_at;";q.Parameters.AddWithValue("$project",projectId.ToString());q.Parameters.AddWithValue("$layer",layer);q.Parameters.AddWithValue("$status",status);await using var r=await q.ExecuteReaderAsync(cancellationToken);var items=new List<ProjectMemoryItem>();while(await r.ReadAsync(cancellationToken))items.Add(Read(r));return items;}
    public async Task<IReadOnlyList<ProjectMemorySource>> GetSourcesAsync(Guid id,CancellationToken cancellationToken=default){await using var c=_database.CreateConnection();await c.OpenAsync(cancellationToken);var q=c.CreateCommand();q.CommandText="SELECT source_type,source_ref FROM project_memory_sources WHERE memory_id=$id;";q.Parameters.AddWithValue("$id",id.ToString());await using var r=await q.ExecuteReaderAsync(cancellationToken);var sources=new List<ProjectMemorySource>();while(await r.ReadAsync(cancellationToken))sources.Add(new(r.GetString(0),r.GetString(1)));return sources;}
    public async Task SetStatusAsync(Guid id,string status,DateTimeOffset updated,CancellationToken cancellationToken=default){await using var c=_database.CreateConnection();await c.OpenAsync(cancellationToken);var q=c.CreateCommand();q.CommandText="UPDATE project_memory_items SET status=$status,updated_at=$updated WHERE id=$id;";q.Parameters.AddWithValue("$id",id.ToString());q.Parameters.AddWithValue("$status",status);q.Parameters.AddWithValue("$updated",updated.ToString("O",CultureInfo.InvariantCulture));await q.ExecuteNonQueryAsync(cancellationToken);}
    private static void Add(SqliteCommand q,ProjectMemoryItem i){q.Parameters.AddWithValue("$id",i.Id.ToString());q.Parameters.AddWithValue("$project",i.ProjectId.ToString());q.Parameters.AddWithValue("$layer",i.Layer);q.Parameters.AddWithValue("$topic",i.Topic);q.Parameters.AddWithValue("$content",i.Content);q.Parameters.AddWithValue("$status",i.Status);q.Parameters.AddWithValue("$created",i.CreatedAt.ToString("O",CultureInfo.InvariantCulture));q.Parameters.AddWithValue("$updated",i.UpdatedAt.ToString("O",CultureInfo.InvariantCulture));q.Parameters.AddWithValue("$certified",i.CertifiedAt is null?DBNull.Value:i.CertifiedAt.Value.ToString("O",CultureInfo.InvariantCulture));}
    private static ProjectMemoryItem Read(SqliteDataReader r)=>new(Guid.Parse(r.GetString(0)),Guid.Parse(r.GetString(1)),r.GetString(2),r.GetString(3),r.GetString(4),r.GetString(5),DateTimeOffset.Parse(r.GetString(6),CultureInfo.InvariantCulture),DateTimeOffset.Parse(r.GetString(7),CultureInfo.InvariantCulture),r.IsDBNull(8)?null:DateTimeOffset.Parse(r.GetString(8),CultureInfo.InvariantCulture));
}
