using Workbench.Core.Tasks;
using Workbench.Storage.Database;
using Workbench.Storage.Tasks;
using Workbench.Storage.Tests.Database;

namespace Workbench.Storage.Tests.Tasks;
public sealed class TaskLifecycleTests
{
 [Fact] public async Task Create_edit_ready_cancel_and_revision_history_roundtrip(){await using var f=await Fixture.CreateAsync();var task=f.Draft;await f.Tasks.CreateAsync(f.Project,task);Assert.Equal(TaskLifecycleStatus.Draft,(await f.Tasks.GetAsync(f.Project,task.TaskId))!.Status);await f.Tasks.UpdateTitleAsync(f.Project,task.TaskId,"Edited");await f.Tasks.UpdateStatusAsync(f.Project,task.TaskId,TaskLifecycleStatus.ReadyToStart);var v2=task.CurrentRevision.CreateSuccessor("g2","reason",TaskRevisionApprover.User);Assert.True(await f.Revisions.CreateSuccessorAsync(f.Project,task.TaskId,task.CurrentRevision.Id,v2));Assert.Equal(2,(await f.Revisions.ListAsync(task.TaskId)).Count);await f.Tasks.UpdateStatusAsync(f.Project,task.TaskId,TaskLifecycleStatus.Cancelled);Assert.Equal(TaskLifecycleStatus.Cancelled,(await f.Tasks.GetAsync(f.Project,task.TaskId))!.Status);}
 [Fact] public async Task Successor_rejects_stale_and_cross_task_previous(){await using var f=await Fixture.CreateAsync();await f.Tasks.CreateAsync(f.Project,f.Draft);var v2=f.Draft.CurrentRevision.CreateSuccessor("g2","r",TaskRevisionApprover.User);Assert.True(await f.Revisions.CreateSuccessorAsync(f.Project,f.Draft.TaskId,f.Draft.CurrentRevision.Id,v2));var v3=v2.CreateSuccessor("g3","r",TaskRevisionApprover.User);Assert.False(await f.Revisions.CreateSuccessorAsync(f.Project,f.Draft.TaskId,f.Draft.CurrentRevision.Id,v3));}
 [Fact] public async Task Concurrent_successors_have_one_winner_and_no_orphan(){await using var f=await Fixture.CreateAsync();await f.Tasks.CreateAsync(f.Project,f.Draft);var a=f.Draft.CurrentRevision.CreateSuccessor("a","a",TaskRevisionApprover.User);var b=f.Draft.CurrentRevision.CreateSuccessor("b","b",TaskRevisionApprover.User);var results=await Task.WhenAll(f.Revisions.CreateSuccessorAsync(f.Project,f.Draft.TaskId,f.Draft.CurrentRevision.Id,a),f.Revisions.CreateSuccessorAsync(f.Project,f.Draft.TaskId,f.Draft.CurrentRevision.Id,b));Assert.Equal(1,results.Count(x=>x));Assert.Equal(2,(await f.Revisions.ListAsync(f.Draft.TaskId)).Count);}
 [Fact] public async Task Historical_snapshot_and_project_scope_remain_unchanged(){await using var f=await Fixture.CreateAsync();await f.Tasks.CreateAsync(f.Project,f.Draft);var v1=f.Draft.CurrentRevision;var v2=v1.CreateSuccessor("g2","r2",TaskRevisionApprover.User);Assert.True(await f.Revisions.CreateSuccessorAsync(f.Project,f.Draft.TaskId,v1.Id,v2));await f.Tasks.UpdateTitleAsync(f.Project,f.Draft.TaskId,"new title");var history=await f.Revisions.ListAsync(f.Draft.TaskId);Assert.Equal(v1.Goal,history[0].Goal);Assert.Equal(v1.Acceptance,history[0].Acceptance);Assert.Empty(await f.Revisions.ListAsync(Guid.NewGuid(),f.Draft.TaskId));}
 private sealed class Fixture:IAsyncDisposable{readonly TemporaryDatabase T;public readonly WorkbenchDatabase Db;public readonly TaskRepository Tasks;public readonly TaskRevisionRepository Revisions;public readonly Guid Project=Guid.NewGuid();public readonly TaskDraft Draft;Fixture(TemporaryDatabase t,WorkbenchDatabase d){T=t;Db=d;Tasks=new(d);Revisions=new(d);var p=ExecutionProfile.Create("p","a","m","r");var id=Guid.NewGuid();var rev=new TaskRevision(id,1,"goal","scope","out",new[]{"accept"},TaskRiskLevel.Low,p,"initial",TaskRevisionApprover.User,DateTimeOffset.UtcNow,null);Draft=new TaskDraft(id,"Title","goal","scope","out",new[]{"accept"},TaskRiskLevel.Low,p,DateTimeOffset.UtcNow,rev);}
 public static async Task<Fixture>CreateAsync(){var t=new TemporaryDatabase();var d=new WorkbenchDatabase(t.DatabasePath);await d.InitializeAsync();var f=new Fixture(t,d);await using var c=d.CreateConnection();await c.OpenAsync();var q=c.CreateCommand();q.CommandText=$"INSERT INTO projects(id,name,root_path,project_type,created_at,last_opened_at) VALUES('{f.Project}','P','C:/P',0,'2026-01-01T00:00:00+00:00','2026-01-01T00:00:00+00:00');";await q.ExecuteNonQueryAsync();return f;}public ValueTask DisposeAsync()=>T.DisposeAsync();}
}
