using Microsoft.Data.Sqlite;
namespace Workbench.Storage.Migrations;
internal static class Migration007LeaderWorkerDelegation
{
 public const long Version = 7;
 public static async Task ApplyAsync(SqliteConnection connection, SqliteTransaction transaction, CancellationToken cancellationToken)
 {
  var command = connection.CreateCommand(); command.Transaction = transaction;
  command.CommandText = "CREATE TABLE IF NOT EXISTS tasks (id TEXT PRIMARY KEY, project_id TEXT NOT NULL, title TEXT NOT NULL, status TEXT NOT NULL CHECK(status IN ('Draft','ReadyToStart','Cancelled')), current_revision_id TEXT NOT NULL, created_at TEXT NOT NULL, updated_at TEXT NOT NULL, cancelled_at TEXT NULL, FOREIGN KEY(project_id) REFERENCES projects(id) ON DELETE CASCADE);" +
  "CREATE TABLE IF NOT EXISTS task_revisions (id TEXT PRIMARY KEY, task_id TEXT NOT NULL, revision_number INTEGER NOT NULL, goal TEXT NOT NULL, scope TEXT NOT NULL, out_of_scope TEXT NOT NULL, acceptance_json TEXT NOT NULL, risk_level TEXT NOT NULL, recommended_provider_id TEXT NOT NULL, recommended_provider_account_id TEXT NOT NULL, recommended_model_profile_id TEXT NOT NULL, recommended_agent_runtime_id TEXT NOT NULL, change_reason TEXT NOT NULL, approved_by TEXT NOT NULL, created_at TEXT NOT NULL, previous_revision_id TEXT NULL, FOREIGN KEY(task_id) REFERENCES tasks(id) ON DELETE CASCADE, UNIQUE(task_id,revision_number));" +
  "CREATE TABLE IF NOT EXISTS worker_executions (id TEXT PRIMARY KEY, project_id TEXT NOT NULL, task_id TEXT NOT NULL, execution_start_revision_id TEXT NOT NULL, execution_start_revision_number INTEGER NOT NULL, current_ack_revision_id TEXT NOT NULL, current_ack_revision_number INTEGER NOT NULL, base_commit TEXT NOT NULL, target_branch TEXT NOT NULL, provider_id TEXT NOT NULL, provider_account_id TEXT NOT NULL, model_profile_id TEXT NOT NULL, agent_runtime_id TEXT NOT NULL, worker_branch TEXT NOT NULL, worker_worktree_path TEXT NOT NULL, state TEXT NOT NULL CHECK(state IN ('Preparing','WorkspaceCreating','WorkspaceCreated','RuntimeStarting','Running','Blocked','Interrupted','CompletedPendingReview','Failed')), agent_session_id TEXT NULL, external_session_id TEXT NULL, working_directory TEXT NULL, recovery_metadata TEXT NULL, created_at TEXT NOT NULL, updated_at TEXT NOT NULL, FOREIGN KEY(project_id) REFERENCES projects(id) ON DELETE CASCADE, FOREIGN KEY(task_id) REFERENCES tasks(id) ON DELETE CASCADE);" +
  "CREATE TABLE IF NOT EXISTS task_events (id TEXT PRIMARY KEY, project_id TEXT NOT NULL, task_id TEXT NOT NULL, execution_id TEXT NULL, event_type TEXT NOT NULL, status TEXT NULL, payload_json TEXT NOT NULL, created_at TEXT NOT NULL, FOREIGN KEY(project_id) REFERENCES projects(id) ON DELETE CASCADE, FOREIGN KEY(task_id) REFERENCES tasks(id) ON DELETE CASCADE);" +
  "CREATE TABLE IF NOT EXISTS permission_requests (id TEXT PRIMARY KEY, task_id TEXT NOT NULL, revision_number INTEGER NOT NULL, requested_capability TEXT NOT NULL, scope TEXT NOT NULL, access_mode TEXT NOT NULL, reason TEXT NOT NULL, risk TEXT NOT NULL, requested_duration_seconds INTEGER NOT NULL, state TEXT NOT NULL, decision TEXT NULL, decided_by TEXT NULL, decided_at TEXT NULL, created_at TEXT NOT NULL, FOREIGN KEY(task_id) REFERENCES tasks(id) ON DELETE CASCADE);" +
  "CREATE TABLE IF NOT EXISTS task_grants (id TEXT PRIMARY KEY, task_id TEXT NOT NULL, capability TEXT NOT NULL, scope TEXT NOT NULL, expiry TEXT NOT NULL, granted_by TEXT NOT NULL, created_at TEXT NOT NULL, FOREIGN KEY(task_id) REFERENCES tasks(id) ON DELETE CASCADE);" +
  "CREATE TABLE IF NOT EXISTS task_clarifications (id TEXT PRIMARY KEY, task_id TEXT NOT NULL, revision_number INTEGER NOT NULL, category TEXT NOT NULL, question_or_conflict TEXT NOT NULL, reason TEXT NULL, created_at TEXT NOT NULL, FOREIGN KEY(task_id) REFERENCES tasks(id) ON DELETE CASCADE);" +
  "CREATE TABLE IF NOT EXISTS worker_completion_packages (id TEXT PRIMARY KEY, execution_id TEXT NOT NULL UNIQUE, task_id TEXT NOT NULL, executed_against_revision_id TEXT NOT NULL, final_report TEXT NOT NULL, evidence_json TEXT NOT NULL, created_at TEXT NOT NULL, FOREIGN KEY(execution_id) REFERENCES worker_executions(id) ON DELETE CASCADE, FOREIGN KEY(task_id) REFERENCES tasks(id) ON DELETE CASCADE);" +
  "CREATE INDEX IF NOT EXISTS ix_tasks_project_status ON tasks(project_id,status); CREATE INDEX IF NOT EXISTS ix_tasks_project_created ON tasks(project_id,created_at); CREATE INDEX IF NOT EXISTS ix_worker_project_state ON worker_executions(project_id,state); CREATE UNIQUE INDEX IF NOT EXISTS ux_worker_active_project ON worker_executions(project_id) WHERE state IN ('Preparing','WorkspaceCreating','WorkspaceCreated','RuntimeStarting','Running','Blocked','Interrupted'); CREATE INDEX IF NOT EXISTS ix_task_events_task_time ON task_events(task_id,created_at); PRAGMA user_version = 7;";
  await command.ExecuteNonQueryAsync(cancellationToken);
 }
}

